name: strack
favicon: null
layout_spectrum: 0.98033
typography_spectrum: 0.57517
title: 'All things stracktacular!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#061711'
    - '#8c959e'
    - '#2d6035'
    - '#fc9979'
    - '#80cf37'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
